# Generated by Django 3.0.3 on 2020-03-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20200228_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='activate/static/images/profile_pics/default.png', upload_to='activate/static/images/profile_pics'),
        ),
    ]
