# Generated by Django 3.0.3 on 2020-03-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_profile_ntnui_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ntnui_membership',
            new_name='NTNUI_medlem',
        ),
    ]
