# Generated by Django 3.0.3 on 2020-03-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_auto_20200310_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anonymous',
            field=models.BooleanField(default=True, verbose_name='anonym'),
        ),
    ]
