# Generated by Django 3.0.3 on 2020-04-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_profile_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='NTNUI_medlem',
            field=models.BooleanField(default=False, verbose_name='Jeg er NTNUI-medlem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='anonymous',
            field=models.BooleanField(default=True, verbose_name='Jeg ønsker å være anonym overfor andre brukere på siden'),
        ),
    ]
