# Generated by Django 3.0.3 on 2020-02-27 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tittel')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_from', models.DateTimeField(verbose_name='fra dato')),
                ('date_to', models.DateTimeField(verbose_name='til dato')),
                ('gear', models.CharField(default='', max_length=200, verbose_name='utstyr')),
                ('max_participants', models.IntegerField(default=0, verbose_name='maks_deltagere')),
                ('registered_users', models.ManyToManyField(blank=True, related_name='events_activity_registered', to=settings.AUTH_USER_MODEL, verbose_name='påmeldte brukere')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_activity_responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
