# Generated by Django 3.0.3 on 2020-02-12 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tittel')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_from', models.DateTimeField(verbose_name='fra dato')),
                ('date_to', models.DateTimeField(verbose_name='til dato')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
