# Generated by Django 3.0.3 on 2020-02-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_activity_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='gear',
            field=models.CharField(default='', max_length=200, verbose_name='utstyr'),
        ),
    ]
