# Generated by Django 3.0.3 on 2020-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200302_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date', 'time_from', 'ntnui_membership'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='ntnui_membership',
            field=models.BooleanField(default=False),
        ),
    ]
