# Generated by Django 3.0.3 on 2020-02-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_activity_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.IntegerField(default=0, verbose_name='maks_deltagere'),
        ),
    ]
