# Generated by Django 3.0.3 on 2020-02-25 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_activity_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='events_activity_registered', to=settings.AUTH_USER_MODEL, verbose_name='påmeldte brukere'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_activity_responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
