# Generated by Django 3.0.3 on 2020-03-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200310_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date', 'time_from', 'krever_NTNUI_medlemskap'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='ntnui_membership',
            new_name='krever_NTNUI_medlemskap',
        ),
    ]
