# Generated by Django 3.0.3 on 2020-03-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200310_1445'),
        ('events', '0004_auto_20200310_1544'),
    ]

    operations = [
    ]
