# Generated by Django 3.0.3 on 2020-03-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_merge_20200311_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date', 'time_from', 'krever_NTNUI_medlemskap'], 'verbose_name_plural': 'Activities'},
        ),
    ]
