# Generated by Django 3.0.3 on 2020-02-25 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_auto_20200225_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='registered_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='events_activity_registered', to=settings.AUTH_USER_MODEL, verbose_name='påmeldte brukere'),
        ),
    ]
