# Generated by Django 3.0.3 on 2020-03-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_merge_20200310_1738'),
        ('events', '0007_activity_price'),
    ]

    operations = [
    ]
