# Generated by Django 3.0.3 on 2020-02-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200225_1531'),
        ('events', '0007_auto_20200225_1549'),
    ]

    operations = [
    ]
