# Generated by Django 3.0.3 on 2020-02-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_merge_20200226_1603'),
        ('events', '0004_activity_max_participants'),
    ]

    operations = [
    ]
