# Generated by Django 3.0.3 on 2020-03-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_merge_20200314_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='oppmøtested',
            field=models.CharField(default='', max_length=200, verbose_name='oppmøtested'),
            preserve_default=False,
        ),
    ]
