# Generated by Django 3.0.3 on 2020-03-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_activity_oppmøtested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='oppmøtested',
            new_name='meeting_place',
        ),
    ]
