# Generated by Django 3.0.3 on 2020-03-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200323_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
